// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Homework2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    //System.setProperty("webdriver.chrome.driver","F:\\chrome-win64\\chrome.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void t01() {
    //T-01. Загрузка раздела главного меню "Все онлайн-курсы"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(968, 676));
    driver.findElement(By.cssSelector(".main__burger-line:nth-child(3)")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".t978__menu-item:nth-child(1) .t978__typo_623893182 > .t978__link-inner")).click();
    vars.put("win5894", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win5894").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t02() {
    //T-02. Загрузка раздела главного меню "Бесплатно"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("БЕСПЛАТНО")).click();
    vars.put("win2845", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2845").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t03() {
    //T-03. Загрузка раздела главного меню "Центр карьеры"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(3) > .main__nav-item")).click();
    vars.put("win3580", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win3580").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t04() {
    //T-04. Загрузка раздела главного меню "Контакты"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(4) > .main__nav-item")).click();
    vars.put("win8313", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win8313").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t05() {
    //T-05. Загрузка раздела главного меню "Медиа"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(5) > .main__nav-item")).click();
    vars.put("win9090", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win9090").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t06() {
    //T-06. Загрузка раздела главного меню "Корпоративное обучение"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(6) > .main__nav-item")).click();
    vars.put("win2628", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2628").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t07() {
    //T-07. Возврат на главную страницу
    driver.get("https://skillfactory.ru/courses");
    driver.findElement(By.cssSelector(".tn-elem__6093552001678370260052 .tn-atom__img")).click();
    driver.close();
  }
  @Test
  public void t08Python() {
    //T-08. Загрузка раздела "Программирование - Python"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Программирование")).click();
    vars.put("win6424", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win6424").toString());
    driver.findElement(By.linkText("Python")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t09() {
    //T-09. Загрузка раздела "Программирование - Веб-разработка"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Программирование")).click();
    vars.put("win5661", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win5661").toString());
    driver.findElement(By.linkText("Веб-разработка")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t10() {
    //T-10. Загрузка раздела "Программирование - Тестирование"
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Программирование")).click();
    vars.put("win2828", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2828").toString());
    driver.findElement(By.linkText("Тестирование")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t11() {
    //T-11. Открытие формы записи на курс
    driver.get("https://skillfactory.ru/courses/programmirovanie");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("#PDEV .card__additional-img")).click();
    vars.put("win896", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win896").toString());
    driver.findElement(By.linkText("Записаться на курс")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t12() {
    //T-12. Ввод имени в форму записи на курс
    driver.get("https://skillfactory.ru/python-developer");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.name("name")).click();
    driver.close();
  }
  @Test
  public void t13email() {
    //T-13. Ввод email в форму записи на курс
    driver.get("https://skillfactory.ru/python-developer");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.name("email")).click();
    driver.close();
  }
  @Test
  public void t14() {
    //T-14. Ввод телефона в форму записи на курс
    driver.get("https://skillfactory.ru/python-developer");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("input_1619420893371")).click();
    driver.close();
  }
  @Test
  public void t15() {
    //T-15. Переход в социальную сеть Дзен из футера
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__7229335731676892134944 .tn-atom__img")).click();
    vars.put("win6944", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win6944").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t16Habr() {
    //T-16. Переход в социальную сеть Habr из футера
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__7229335731676892134965 > .tn-atom")).click();
    vars.put("win7081", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win7081").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t17Youtube() {
    //T-17. Переход в социальную сеть Youtube из футера
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__7229335731676892134988 > .tn-atom")).click();
    vars.put("win9948", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win9948").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void t18Java() {
    //T-18. Переход в раздел "Курсы Java" из футера
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Курсы Java")).click();
    driver.close();
  }
  @Test
  public void t19() {
    //T-19. Ввод почты для подписки на новости
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector(".t-input-group_em:nth-child(1) .t-input")).click();
    driver.close();
  }
  @Test
  public void t20() {
    //T-20. Вызов формы вопроса в меню "Контакты"
    driver.get("https://skillfactory.ru/contacts");
    driver.findElement(By.cssSelector(".tn-elem__6188040781689910041838 > .tn-atom")).click();
    driver.close();
  }
}
